name: DevOps

on:
  push:
    branches:
      - dev-v4.0.0
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        run: |
          yarn install
      - name: Lint
        run: |
          yarn lint
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        run: |
          yarn install
      - name: Prettier
        run: |
          yarn prettier:check
  build:
    name: Build Webpack Bundle
    runs-on: ubuntu-latest
    needs: [ lint, prettier ]
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          yarn install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          yarn webpack:build-prod
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ lint, prettier, build ]
    steps:
      - name: Install Dependencies
      uses: actions/checkout@v2
      run: |
        yarn install
      - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
      - name: Build
      run: |
        yarn webpack:build-prod
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mctzock/incode-editor
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}