name: Prettier
on:
  push:
    branches: [ latest, main ]
  pull_request:
    branches: [ latest, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write src
